all:
	gcc markov_chain_metropolis.c ranlux-3.4/ranlxs.c ranlux-3.4/ranlux_common.c -o markov_chain_metropolis -lm -std=c99 -pedantic -fstrict-aliasing -Wall -Wstrict-prototypes -Werror -O2
	g++ markov_chain_transition_matrix.cpp -o markov_chain_transition_matrix -lm

