all:
	gcc metropolis_random.c ranlux-3.4/ranlxs.c ranlux-3.4/ranlux_common.c -o metropolis_random -lm -std=c99 -pedantic -fstrict-aliasing -Wall -Wstrict-prototypes -Werror -O2
	gcc transition_matrix_metropolis_random.c ranlux-3.4/ranlxs.c ranlux-3.4/ranlux_common.c -o transition_matrix_metropolis_random -lm -std=c99 -pedantic -fstrict-aliasing -Wall -Wstrict-prototypes -Werror -O2

